name: Deploy Laravel App to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up SSH key for authentication
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}

      # Step 3: Add the Lightsail server's SSH key to known_hosts
      - name: Add SSH Host Key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.AWS_SERVER_IP }} >> ~/.ssh/known_hosts

      # Step 4: Copy files to server using rsync
      - name: Copy files to server
        run: |
          rsync -avz --no-times --exclude '.git*' --exclude 'node_modules' ./ ubuntu@${{ secrets.AWS_SERVER_IP }}:/var/www/html/beautifyskincare

      # Step 5: SSH commands to restart Apache and run other commands
      - name: SSH Commands to Restart Apache
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_SERVER_IP }} << 'EOF'
            cd /var/www/html/beautifyskincare
            git pull origin main
            composer install --no-interaction --prefer-dist
            php artisan migrate --force
            sudo systemctl restart apache2
          EOF
